theme: minima
title: Comité's blog 
author: Adão Pinto
email: filipepinto1801@gmail.com
description: Boas! vais ficar a conhecer as mais lindas histórias de 4 bananas em Vila Real

# social links
twitter_username: therealfdonis
github_username:  therealdonis

show_excerpts: true # set to false to remove excerpts on the homepage
